version: '3.8'

services:
  wen玩雅集:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: wenwan-shop
    restart: unless-stopped
    environment:
      - NODE_ENV=production
